### ISSUE TITLE
🔊 Feedback on the documentation.

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/documentation#324]
Feel free to leave your suggestion and idea on the documentation, we are constantly working towards a better doc for everyone.

**Comment by donocode** [comment]
As a v5 user it seems pretty awkward to be able to use the docs now that v6 is out, there is a v5/v6 toggle on the api page but when viewing v5 the api is v5 yet the examples are for v6, specifically I am looking at the `Controller` api and the example uses the v6 render prop.

Rather than overcomplicating things I would expect to be able to click some global toggle of v5/v6 and view the documentation as it was when that release released. Apart from this the documentation and the site are very good, really one of the best documentation sites I have seen for any library.

**Comment by bluebill1049** [comment]
wow, that's a bug, @donocode that shouldn't be the case, i have duplicated v5 doc and the cab should be associated to v5. will take a look into this.

**Comment by pmaier983** [comment]
Was just about to respond. Seems there was a mixup in the controller example. Ill check in and get back!
