### ISSUE TITLE
resource page with better filter, tag and search

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/documentation#656]
https://react-hook-form.com/resources

our resource page is getting way too big at the moment, it's almost impossible to look for the relevant resources. would be possible to a database host those resources with better filter and tag functionality. currently, the data source is hosted in faunadb.

**Comment by pmaier983** [comment]
So I'm not sure what you mean when you mention faunadb, but I can think of two solutions for the resources page.

1. Have a V6/V7 toggle button. This solution would work fine in the short run, but as RHF gets updated, multiple buttons would clutter the UI & might lead people to not even consider looking at slightly older resources. 

2. Have a search bar that is basically just a filter. We could also add tags to each of the posts, so that the filter doesn't just filter on Title & Summary!

I def lean towards the direction of #2, but I don't know what you're thinking when it comes to faunadb (Option 3?)

**Comment by bluebill1049** [comment]
thanks, @pmaier983 yes option 2 is better, faundadb: https://fauna.com/ we use that at the moment.

**Comment by pmaier983** [comment]
Out of curiosity why are we using a db for the resources? It looks like we are just fetching a bunch of text and links. Does it slow page loads down too much to just load everything upfront, storing the links/summaries etc. in JSON? 

As of now I'm planning on just letting fauna do the initial fetch and then filtering the data it returns via a search input.

But I was also thinking about totally cutting fauna out, storing the data in JSON & filtering the JSON.

**Comment by bluebill1049** [comment]
Sounds good to me. I was too lazy with update the file, I build a little UI and send post request to the db to update the tutorial and video.
