### ISSUE TITLE
issue: builder Radio input 

### ISSUE THREAD

**Issue by BrainDev333** [react-hook-form/documentation#834]
### Version Number

V7

### Codesandbox/Expo snack

the bug is on the builder

### Steps to reproduce

1. Go to '[builder](https://react-hook-form.com/form-builder)'
2. add type 'radio' 
3. nothing appears on code 

### Expected behaviour

Each time you add an input in the builder the code generate automatically, which is not the case with radio button input.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdaltonLeite** [comment]
@BrainDev333 The bug is because you don't add a **Options** when you create a radio input, if you add Options the code it will generate. 

I proposal a change on the page build to add a required validate on input **Radio** and **Select**. 


PR: https://github.com/react-hook-form/documentation/pull/861

**Comment by AdaltonLeite** [comment]
@BrainDev333  @bluebill1049  I think we close this issue when we merge the #866, what do you think?

**Comment by bluebill1049** [comment]
thanks @AdaltonLeite for the update 🙉
